In [1]:
"""
Lecture: TensorFlow Basics
This file demonstrates core TensorFlow concepts step-by-step.
"""

# ======================================================
# 1. Importing TensorFlow
# ======================================================

import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)

# ======================================================
# 2. What is TensorFlow?
# ======================================================

# TensorFlow is an open-source library for:
# - Numerical computation
# - Deep Learning
# - Neural Networks
print("TensorFlow is used for deep learning and numerical computation")

# ======================================================
# 3. Tensors (Core Data Structure)
# ======================================================

print("\nTENSOR CREATION")

# Creating tensors from Python lists
a = tf.constant([1, 2, 3])
b = tf.constant([[1, 2], [3, 4]])

print("Tensor a:", a)
print("Tensor b:\n", b)

# Rank (dimensions)
print("Rank of a:", tf.rank(a))
print("Shape of b:", b.shape)

# ======================================================
# 4. Tensor Data Types
# ======================================================

x = tf.constant([1, 2, 3], dtype=tf.float32)
y = tf.constant([4, 5, 6], dtype=tf.int32)

print("x dtype:", x.dtype)
print("y dtype:", y.dtype)

# ======================================================
# 5. Tensor Operations
# ======================================================

print("\nTENSOR OPERATIONS")

# Element-wise operations
print("Addition:", tf.add(x, tf.cast(y, tf.float32)))
print("Multiplication:", tf.multiply(x, tf.cast(y, tf.float32)))

# Matrix multiplication
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[5, 6], [7, 8]])

print("Matrix multiplication:\n", tf.matmul(m1, m2))

# ======================================================
# 6. Conversion Between NumPy & TensorFlow
# ======================================================

print("\nNUMPY ↔ TENSORFLOW")

np_arr = np.array([10, 20, 30])
tf_tensor = tf.convert_to_tensor(np_arr)

print("NumPy array:", np_arr)
print("Converted to tensor:", tf_tensor)

print("Back to NumPy:", tf_tensor.numpy())

# ======================================================
# 7. Variables (Trainable Parameters)
# ======================================================

print("\nVARIABLES")

# Variables are mutable tensors
w = tf.Variable([1.0, 2.0, 3.0])
print("Initial variable:", w)

w.assign_add([1.0, 1.0, 1.0])
print("After update:", w)

# ======================================================
# 8. Automatic Differentiation (Gradient Tape)
# ======================================================

print("\nAUTOMATIC DIFFERENTIATION")

x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2

dy_dx = tape.gradient(y, x)
print("dy/dx at x=3:", dy_dx)

# ======================================================
# 9. Simple Neural Network (Keras API)
# ======================================================

print("\nSIMPLE NEURAL NETWORK")

# Creating a simple model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(1)
])

model.summary()

# ======================================================
# 10. Compiling the Model
# ======================================================

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

print("Model compiled successfully")

# ======================================================
# 11. Dummy Training Example
# ======================================================

# Dummy data
X = np.random.random((10, 4))
y = np.random.random((10, 1))

# Training
model.fit(X, y, epochs=3, verbose=1)

# ======================================================
# End of Lecture
# ======================================================

print("\n✅ END OF TENSORFLOW INTRODUCTION")


TensorFlow version: 2.19.0
TensorFlow is used for deep learning and numerical computation

TENSOR CREATION
Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Rank of a: tf.Tensor(1, shape=(), dtype=int32)
Shape of b: (2, 2)
x dtype: <dtype: 'float32'>
y dtype: <dtype: 'int32'>

TENSOR OPERATIONS
Addition: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Multiplication: tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
Matrix multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

NUMPY ↔ TENSORFLOW
NumPy array: [10 20 30]
Converted to tensor: tf.Tensor([10 20 30], shape=(3,), dtype=int64)
Back to NumPy: [10 20 30]

VARIABLES
Initial variable: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
After update: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

AUTOMATIC DIFFERENTIATION
dy/dx at x=3: tf.Tensor(6.0, s

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 49 (196.00 B)

 Trainable params: 49 (196.00 B)

 Non-trainable params: 0 (0.00 B)

Model compiled successfully
Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.4754 - mae: 0.6372
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step - loss: 0.4701 - mae: 0.6331
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.4649 - mae: 0.6292

✅ END OF TENSORFLOW INTRODUCTION
